<#
  Outerplane gear-solver - one-shot capture.
  Arms the MITM pipeline, relaunches the game, and live-decodes the account data
  into .\out\ as clean JSON. Leaves the pipeline armed so any later in-game data
  fetch keeps decoding automatically. Run .\disarm.ps1 to tear everything down.

  Prereqs (one time):
    - LDPlayer 9 instance running, ADB debugging = Local connection.
    - LDPlayer Root toggle ON (needed to install the CA cert + iptables).
      The game launches fine with it on.
  Usage:
    powershell -ExecutionPolicy Bypass -File .\capture.ps1
    powershell -ExecutionPolicy Bypass -File .\capture.ps1 -NoRelaunch   # just arm, don't restart the game
#>
param(
  [string]$Device   = "127.0.0.1:5555",
  [string]$Adb      = "C:\LDPlayer\LDPlayer9\adb.exe",
  [string]$Mitmdump = "C:\Program Files\mitmproxy\bin\mitmdump.exe",
  # Where decoded JSON gets written. Defaults to .\out\ next to the script
  # (the historical dev-time behavior). The Electron prod build overrides
  # this with a path under the user's appData so the install dir stays
  # read-only and capture survives upgrades.
  [string]$Out      = $null,
  # Override mitmproxy's confdir (default ~/.mitmproxy). The Electron prod
  # build points this at the bundled CA dir so the dev's personal CA never
  # ships, and so that the bundled cert pushed to Android matches the CA
  # this mitmdump uses.
  [string]$MitmConfDir = $null,
  # Where to find the Android-hash cert file pushed to the device. Defaults
  # to the dev-committed cert (cert/c8750f0d.0); prod overrides to the
  # dedicated prod-cert dir generated by fetch-binaries.mjs.
  [string]$CertDir  = $null,
  [int]$TimeoutSec  = 150,
  [switch]$NoRelaunch
)
$ErrorActionPreference = "Stop"
$Root   = $PSScriptRoot
if (-not $Out) { $Out = Join-Path $Root "out" }
if (-not $CertDir) { $CertDir = Join-Path $Root "cert" }
$Pkg    = "com.smilegate.outerplane.stove.google"
$CertHashFile = "c8750f0d.0"   # mitmproxy CA, Android subject_hash_old name

# Adb wrapper bound to the configured device. `MuteAdb` discards both stdout
# AND stderr from native calls - adb / monkey / iptables-shells dump a lot of
# noise (monkey echoes its parsed args to stderr, adb push echoes throughput,
# etc.) and that noise lands in the Electron capture log without it.
#
# The local $ErrorActionPreference override is what actually silences the
# noise: PS 5.1 wraps every stderr line from a native command into a
# NativeCommandError BEFORE the `2>$null` redirect kicks in, so the
# error-record exists even with the redirect - and with $EAP=Stop (set at
# the top of the script), that record terminates the whole pipeline. By
# locally flipping $EAP to SilentlyContinue we let the wrapped records be
# discarded silently. The redirect is kept as belt-and-suspenders in case
# we ever drop $EAP=Stop globally.
function Adb { & $Adb -s $Device @args }
function MuteAdb {
  $ErrorActionPreference = "SilentlyContinue"
  & $script:Adb -s $Device @args 2>$null | Out-Null
}
function Su($cmd) { & $script:Adb -s $Device shell "su -c '$cmd'" }

function Die($m) { Write-Host "x  $m" -ForegroundColor Red; exit 1 }
function Ok($m)  { Write-Host "v  $m" -ForegroundColor Green }
function Info($m){ Write-Host ">  $m" -ForegroundColor Cyan }
function Warn($m){ Write-Host "!  $m" -ForegroundColor Yellow }

# --- preflight ---
if (-not (Test-Path $Adb))      { Die "adb not found: $Adb" }
if (-not (Test-Path $Mitmdump)) { Die "mitmdump not found: $Mitmdump" }
New-Item -ItemType Directory -Force -Path $Out | Out-Null

Info "Connecting to ADB ($Device)..."
MuteAdb connect $Device
$state = (Adb get-state) 2>$null
if ($state -ne "device") { Die "Device $Device not ready (state=$state). Launch the emulator and enable ADB." }
Ok "Connected: $Device"

$id = Su "id" 2>$null
if ($id -notmatch "uid=0") { Die "Root unavailable (su failed). Enable the Root toggle in your emulator and restart the instance." }
Ok "Root access verified"

# --- 1. system cert (bind mount, idempotent) ---
$certPresent = Su "ls /system/etc/security/cacerts/$CertHashFile 2>/dev/null"
if ($certPresent -match $CertHashFile) {
  Ok "MITM cert already in system store"
} else {
  Info "Installing MITM cert (bind mount)..."
  MuteAdb push (Join-Path $CertDir $CertHashFile) "/sdcard/$CertHashFile"
  MuteAdb push (Join-Path $Root "scripts\bind_cert.sh") "/sdcard/bind_cert.sh"
  Su "sh /sdcard/bind_cert.sh" | Out-Null
  $certPresent = Su "ls /system/etc/security/cacerts/$CertHashFile 2>/dev/null"
  if ($certPresent -notmatch $CertHashFile) { Die "Cert install failed" }
  Ok "MITM cert installed"
}

# --- 2. start mitmproxy reverse proxy + addon (live decode) ---
# Kill any stale daemon from a previous arm so we don't leak processes.
$pidFile = Join-Path $Out ".mitm.pid"
if (Test-Path $pidFile) {
  $old = Get-Content $pidFile -ErrorAction SilentlyContinue
  if ($old) { Stop-Process -Id $old -Force -ErrorAction SilentlyContinue }
  Remove-Item $pidFile -ErrorAction SilentlyContinue
}
Remove-Item (Join-Path $Out ".captured") -ErrorAction SilentlyContinue

$env:OP_OUT = $Out
$log = Join-Path $Out "mitm.log"
$flows = Join-Path $Out "game.flows"
# Start-Process w/ -ArgumentList does NOT auto-quote args containing spaces on
# Windows PS 5.1 (see PowerShell/PowerShell#5576). Wrap any path arg whose
# value can contain whitespace (here: $Root, $flows) - else `mitmdump -s ...\Projet perso\...\addon.py`
# is parsed as two args and mitmdump dies with "No such script".
function Quote($s) { if ($s -match '\s') { '"' + $s + '"' } else { $s } }
$mitmArgs = @(
  "--mode","reverse:https://glb-game.outerplane.vagames.co.kr:38001@9001",
  "--mode","reverse:https://glb-login.outerplane.vagames.co.kr:38002@9002",
  "--listen-host","0.0.0.0",
  "-s", (Quote (Join-Path $Root "addon.py")),
  "-w", (Quote $flows),
  "--set","flow_detail=0"
)
# Override mitmproxy's confdir when one was passed (Electron prod): the
# bundled CA must match the cert we push to the device a few lines above,
# otherwise the TLS handshake fails. In dev mode this is empty and mitmdump
# falls back to ~/.mitmproxy/ as usual.
# The value MUST be wrapped through Quote(): when Start-Process below passes
# the array to CreateProcess unquoted, an unquoted space in the path splits
# the arg in two and mitmdump interprets the tail as a filter expression
# ("Invalid filter expression: 'perso\\...\\prod-cert'").
if ($MitmConfDir) { $mitmArgs += @("--set", (Quote "confdir=$MitmConfDir")) }
Info "Starting mitmproxy (reverse-proxy + XOR decoder)..."
$proc = Start-Process -FilePath $Mitmdump -ArgumentList $mitmArgs -PassThru -WindowStyle Hidden `
          -RedirectStandardOutput $log -RedirectStandardError "$log.err"
$proc.Id | Out-File -Encoding ascii $pidFile
Start-Sleep -Seconds 3
if ($proc.HasExited) { Die "mitmdump exited (see $log.err)" }
Ok "mitmproxy active (pid $($proc.Id)) on ports 9001 / 9002"

# --- 3. adb reverse tunnel + iptables redirect (idempotent) ---
Info "Setting up ADB reverse tunnel + iptables redirect..."
MuteAdb reverse tcp:9001 tcp:9001
MuteAdb reverse tcp:9002 tcp:9002
MuteAdb push (Join-Path $Root "scripts\redir.sh") "/sdcard/redir.sh"
Su "sh /sdcard/redir.sh" | Out-Null
# Neutralize any leftover Android http_proxy setting so the game's BestHTTP/2
# traffic only goes through our iptables redirect, not a stray system proxy.
MuteAdb shell settings put global http_proxy ":0"
Ok "Pipeline armed (38001 -> 9001, 38002 -> 9002)"

# --- 4. relaunch the game so it triggers the /user/* fetches ---
if (-not $NoRelaunch) {
  Info "Relaunching Outerplane..."
  MuteAdb shell am force-stop $Pkg
  MuteAdb shell "monkey -p $Pkg -c android.intent.category.LAUNCHER 1"
  # Auto-tap "TOUCH TO START" a few times after the splash loads.
  Start-Sleep -Seconds 12
  1..6 | ForEach-Object { MuteAdb shell input tap 880 400; Start-Sleep -Milliseconds 2500 }
}

# --- 5. wait for the inventory snapshot to land ---
Info "Waiting for /user/item (timeout: ${TimeoutSec}s)..."
$captured = $false
$deadline = (Get-Date).AddSeconds($TimeoutSec)
while ((Get-Date) -lt $deadline) {
  if (Test-Path (Join-Path $Out ".captured")) { $captured = $true; break }
  Start-Sleep -Seconds 2
}

if (-not $captured) {
  Write-Host ""
  Warn "Inventory not captured yet - pipeline stays armed."
  Warn "Just walk to the lobby in-game and the snapshots will land in:"
  Warn "  $Out"
  exit 2
}

Ok "Inventory captured + decoded"

# --- 6. tiny summary (gear / hero counts) ---
$summary = @"
import json,os
o=r'$Out'
def load(n):
  p=os.path.join(o,n)
  return json.load(open(p,encoding='utf-8')) if os.path.exists(p) else None
it=load('user_item.json'); ch=load('user_character.json')
if it:
  il=it['ItemList']; eq=[x for x in il if x['CharUID']!='0']
  print('   %d gear pieces (%d equipped, %d free)'%(len(il),len(eq),len(il)-len(eq)))
if ch:
  cl=ch.get('CharList',[]); print('   %d characters'%len(cl))
"@
$tmp = Join-Path $env:TEMP "op_summary.py"
$summary | Out-File -Encoding utf8 $tmp
# Best-effort summary via python. Jean kevin's packaged build may not have
# python on PATH (mitmdump ships its own bundled interpreter that we don't
# expose). Swallow the failure - the .captured sentinel is what callers act
# on, the summary is pure cosmetic.
try { & python $tmp 2>$null } catch {}
# The renderer leaves the pipeline ARMED after exit 0 (see App.tsx
# runCapture) so the user can open the Codex (Hero Archive) and Gift screens
# in-game — those fire /archive/info + /gift/info (codex level + geas) that
# the lobby auto-tap never reaches. The user clicks Disarm once done;
# mitmdump is also torn down on app quit (disarmIfArmed on before-quit).
Info "Inventory captured. Pipeline stays armed: open the Codex and Gift screens in-game to grab codex + geas, then click Disarm."
