/**
 * Runtime provisioning of mitmdump.exe — downloaded on first capture instead
 * of shipping in the installer.
 *
 * Why: bundling the mitmproxy binaries got the NSIS installer flagged by AV
 * heuristics (Varist classifies mitmweb.exe as a potentially-unwanted
 * application, DrWeb piggybacks with a generic trojan signature). Keeping the
 * installer clean and pulling the official build from downloads.mitmproxy.org
 * at first use sidesteps that: users install a small clean setup, and the
 * downloaded zip is verified against the SHA-256 pinned below before anything
 * gets executed.
 *
 * Only mitmdump.exe is kept (the zip's three exes are self-contained;
 * mitmproxy.exe / mitmweb.exe are unused by the capture pipeline). The exe
 * lands under `<userData>/bin/mitmproxy/<version>/` — versioned dir so a
 * pinned-version bump naturally re-provisions, and userData because the
 * install dir stays read-only.
 *
 * Keep MITMPROXY_VERSION + MITMPROXY_SHA256 in sync with
 * `scripts/fetch-binaries.mjs`, which still downloads the same zip at build
 * time (the prod CA is generated by running mitmdump during packaging).
 */
import { existsSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { rename } from "node:fs/promises";
import { join } from "node:path";
import { app } from "electron";
import { IS_DEV } from "./paths.js";
import { dlog, dwarn } from "./log.js";
import { downloadVerified, expandZip } from "./download.js";

export const MITMPROXY_VERSION = "12.1.2";
export const MITMPROXY_SHA256 = "81c268b4d4965899f59043201bd0707075c5b820310be382b2fd41c554f370a2";
const MITMPROXY_URL = `https://downloads.mitmproxy.org/${MITMPROXY_VERSION}/mitmproxy-${MITMPROXY_VERSION}-windows-x86_64.zip`;

/** Dev machines use the system-wide mitmproxy install (same default as
 *  capture.ps1); only packaged builds provision into userData. */
const DEV_MITMDUMP = "C:\\Program Files\\mitmproxy\\bin\\mitmdump.exe";

function binRoot(): string {
  return join(app.getPath("userData"), "bin", "mitmproxy");
}

/** Absolute path of the mitmdump.exe the capture pipeline should use. In prod
 *  the file only exists after `ensureMitmdump()` resolved at least once. */
export function mitmdumpPath(): string {
  return IS_DEV ? DEV_MITMDUMP : join(binRoot(), MITMPROXY_VERSION, "mitmdump.exe");
}

/** Download → verify → extract, reporting human-readable progress through
 *  `log` (the capture console in the renderer). Concurrent callers share the
 *  same in-flight provisioning. No-op when the exe is already in place. */
let inflight: Promise<void> | null = null;
export function ensureMitmdump(log: (line: string) => void): Promise<void> {
  if (existsSync(mitmdumpPath())) return Promise.resolve();
  if (IS_DEV) {
    return Promise.reject(new Error(`mitmdump not found at ${DEV_MITMDUMP} — install mitmproxy or fix the dev path`));
  }
  if (!inflight) {
    inflight = provision(log).finally(() => { inflight = null; });
  }
  return inflight;
}

async function provision(log: (line: string) => void): Promise<void> {
  const root = binRoot();
  const destDir = join(root, MITMPROXY_VERSION);
  // Must end in `.zip` — PowerShell's Expand-Archive refuses any other
  // extension outright ("does not match the .zip file extension").
  const zipPath = join(root, "download.zip");
  const stageDir = join(root, "stage");
  mkdirSync(root, { recursive: true });

  log(`>  First capture on this machine — downloading mitmproxy ${MITMPROXY_VERSION} (~80 MB, one-time)...`);
  dlog("capture", `fetch ${MITMPROXY_URL}`);
  await downloadVerified(MITMPROXY_URL, zipPath, MITMPROXY_SHA256, log, "mitmproxy download").catch((err: Error) => { dwarn("capture", "download failed:", err.message); throw err; });

  log(">  Checksum OK - extracting mitmdump.exe...");
  rmSync(stageDir, { recursive: true, force: true });
  try {
    expandZip(zipPath, stageDir);
  } catch (err) {
    dwarn("capture", "Expand-Archive failed:", (err as Error).message);
    throw err;
  }
  const staged = join(stageDir, "mitmdump.exe");
  if (!existsSync(staged)) throw new Error("mitmdump.exe missing from the mitmproxy zip");

  // Move only the exe we use into the versioned dir, then drop the zip, the
  // stage (mitmproxy.exe / mitmweb.exe) and any previous version's dir.
  mkdirSync(destDir, { recursive: true });
  await rename(staged, join(destDir, "mitmdump.exe"));
  rmSync(stageDir, { recursive: true, force: true });
  rmSync(zipPath, { force: true });
  for (const entry of readdirSync(root)) {
    if (entry !== MITMPROXY_VERSION) rmSync(join(root, entry), { recursive: true, force: true });
  }
  dlog("capture", `mitmdump ${MITMPROXY_VERSION} ready at ${destDir}`);
  log(`v  mitmproxy ready.`);
}
