/**
 * Resolve all the on-disk paths the Electron main process needs, in a way that
 * works both unpacked (dev / `npm run desktop:dev` from inside the monorepo)
 * and packaged (NSIS installer drop on a user's machine).
 *
 * Layout assumptions:
 *  - Dev: the compiled main lives at `apps/desktop/dist/main.js`; all repo
 *    artefacts (data/derived, tools/capture, apps/renderer/dist, the outerpedia
 *    image checkout) live at known offsets relative to the repo root.
 *  - Prod: `electron-builder` copies the bundled trees under
 *    `process.resourcesPath` (see the `extraResources` mapping in this
 *    package's package.json). Anything that needs to be written at runtime
 *    (capture out/, mitm pid file, …) is stored under
 *    `app.getPath("userData")` so the install dir stays read-only.
 */
import { app } from "electron";
import { existsSync } from "node:fs";
import { dirname, join, normalize } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

export const IS_DEV = !app.isPackaged;

/** Monorepo root (../../.. from apps/desktop/dist/main.js). Only meaningful in
 *  dev — in prod the equivalent trees live under `process.resourcesPath`. */
export const REPO_ROOT = normalize(join(here, "..", "..", ".."));

/** Root of the bundled resources tree. Prod uses `resourcesPath`; dev maps
 *  every consumer back to the matching repo directory. */
const RES = IS_DEV ? REPO_ROOT : process.resourcesPath;

/**
 * Persistent cache root for assets + game data synced from the outerpedia repo.
 *  - dev : `<repo>/.cache/outerpedia` (gitignored — the repo trees take over)
 *  - prod: `<userData>/outerpedia-cache` (install dir stays read-only)
 * Everything synced from GitHub at launch lands here so the app updates with
 * game patches without shipping a new build.
 */
export const CACHE_ROOT = IS_DEV ? join(REPO_ROOT, ".cache", "outerpedia") : join(app.getPath("userData"), "outerpedia-cache");

/** Image cache root — `img-cache.ts` writes assets under `<dir>/images/...`. */
export const IMG_CACHE_DIR = CACHE_ROOT;

/** Persisted last-synced repo commit SHA (the data-sync gate + image pin). */
export const REPO_SHA_STATE = join(CACHE_ROOT, "repo-sha.json");

/** Raw game tables build.mjs consumes. Dev uses the committed repo tree; prod
 *  downloads them into the writable cache. */
export const GAME_DIR = IS_DEV ? join(REPO_ROOT, "data", "game") : join(CACHE_ROOT, "game");

/** Mirror of the outerpedia-only build inputs (data/equipment, json2 extras,
 *  damage-calc/buffs). Null in dev (build.mjs reads the checkout via
 *  findOuterpedia); a downloaded mirror in prod. */
export const SYNC_DIR: string | null = IS_DEV ? null : join(CACHE_ROOT, "synced");

/** Derived game data — `data/derived/*.json` consumed by the renderer. Dev uses
 *  the committed repo tree; prod uses the writable cache (rebuilt on each repo
 *  update, seeded from BUNDLED_DERIVED on first launch). */
export const DERIVED = IS_DEV ? join(REPO_ROOT, "data", "derived") : join(CACHE_ROOT, "derived");

/** Read-only derived tree shipped in the installer (extraResources). Used only
 *  in prod as the first-launch seed for the writable DERIVED cache. */
export const BUNDLED_DERIVED = join(RES, "data", "derived");

/** Capture pipeline scripts + cert + mitmproxy addon. PowerShell entrypoints
 *  are `capture.ps1` / `disarm.ps1`. */
export const CAPTURE_DIR = IS_DEV ? join(REPO_ROOT, "tools", "capture") : join(RES, "tools", "capture");

/** Captured account JSON — `user_item.json` etc. In dev this is the repo
 *  output dir so an existing capture stays visible; in prod we keep capture
 *  output under userData so it survives upgrades and the install dir stays
 *  read-only. */
export const CAPTURE_OUT = IS_DEV
  ? join(CAPTURE_DIR, "out")
  : join(app.getPath("userData"), "capture-out");

/** Built renderer (apps/renderer/dist) — served by the embedded HTTP server in
 *  prod; ignored in dev where Vite serves the same files with HMR. */
export const RENDERER_DIST = IS_DEV ? join(REPO_ROOT, "apps", "renderer", "dist") : join(RES, "renderer", "dist");

/** Bundled adb.exe (+ AdbWinApi.dll / AdbWinUsbApi.dll alongside). The dev
 *  fallback points at the LDPlayer-installed copy — the bundled tree only
 *  exists after `scripts/fetch-binaries.mjs` was run, which is a prod-only
 *  concern. */
export const BUNDLED_ADB = IS_DEV
  ? "C:\\LDPlayer\\LDPlayer9\\adb.exe"
  : join(RES, "bin", "adb", "adb.exe");

/** Bundled mitmdump.exe. Same dev/prod split as ADB. */
export const BUNDLED_MITMDUMP = IS_DEV
  ? "C:\\Program Files\\mitmproxy\\bin\\mitmdump.exe"
  : join(RES, "bin", "mitmproxy", "mitmdump.exe");

/** Bundled mitmproxy CA dir — contains both the `mitmproxy-ca.pem` (private
 *  key + cert, used by mitmdump via `--set confdir=...`) and the
 *  Android-hash named `c8750f0d.0` (pushed to the device). Generated by
 *  `scripts/fetch-binaries.mjs` so the dev's personal ~/.mitmproxy/ never
 *  ships in the installer. Unused in dev — the script defaults at
 *  capture.ps1 take over there. */
export const BUNDLED_PROD_CERT_DIR = IS_DEV
  ? join(REPO_ROOT, "apps", "desktop", "resources", "prod-cert")
  : join(RES, "prod-cert");

/** Outerpedia-v2 public images checkout - only used in dev (the Vite
 *  middleware already mounts these). Prod uses the BUNDLED_IMG subset
 *  above + outerpedia.com fallback. */
export function findOuterpediaImagesDev(): string | null {
  const env = process.env.OUTERPEDIA_PATH;
  const candidates = [
    env ? `${env.replace(/\\/g, "/")}/public/images` : null,
    "C:/Users/Sevih/Documents/Projet perso/outerpedia-v2/public/images",
    "C:/Users/Sevih/Documents/dev/outerpedia/public/images",
  ].filter((p): p is string => Boolean(p));
  for (const p of candidates) if (existsSync(p)) return normalize(p);
  return null;
}

/** Stat-locks JSON — committable baseline that the renderer reads/writes via
 *  /api/stat-locks. Dev uses the repo path so git history works; prod stores
 *  the user's edits under userData so the install dir stays read-only. */
export const STAT_LOCKS = IS_DEV
  ? join(REPO_ROOT, "data", "stat-locks.json")
  : join(app.getPath("userData"), "stat-locks.json");

/** Manual capture-device override (adb path + device serial) set in
 *  Settings → Setup. User-specific, never committed — dev keeps it in the
 *  gitignored cache, prod under userData. Mirrors the path the Vite dev
 *  middleware computes so the override survives a dev↔packaged swap. */
export const MANUAL_DEVICE = IS_DEV
  ? join(REPO_ROOT, ".cache", "manual-device.json")
  : join(app.getPath("userData"), "manual-device.json");
