/**
 * In-process HTTP server that hosts everything the renderer needs:
 *  - Built `apps/renderer/dist/*` at `/`
 *  - `/gamedata/*`  → DERIVED game data (data/derived in dev, bundled tree in prod)
 *  - `/captured/*`  → captured account JSON (tools/capture/out in dev, userData in prod)
 *  - `/img/*`       → bundled sprites / disk cache / img.outerpedia.com (R2)
 *  - `/api/capture/{run,disarm,status}` → wraps the PowerShell pipeline (emulator source)
 *  - `/api/steam/{status,install,uninstall,launch}` → Steam source (BepInEx plugin)
 *  - `/api/stat-locks` GET/POST → stat regression locks
 *
 * Everything but the renderer's own files is the shared API handler
 * (api-handler.ts) — the Vite dev middleware (apps/renderer/vite.config.ts)
 * mounts the same handler, so `npm run desktop:dev` and a packaged build
 * behave identically. ETag-based revalidation on data files keeps the
 * renderer fast after the first hit; images use a 1-day max-age.
 */
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { spawn } from "node:child_process";
import { existsSync, mkdirSync, statSync } from "node:fs";
import { join, normalize } from "node:path";
import {
  BUNDLED_ADB,
  BUNDLED_IMG,
  BUNDLED_PROD_CERT_DIR,
  CAPTURE_DIR,
  CAPTURE_OUT,
  DERIVED,
  IMG_CACHE_DIR,
  MANUAL_DEVICE,
  REPO_SHA_STATE,
  IS_DEV,
  STAT_LOCKS,
  RENDERER_DIST,
  SCRATCH_DIR,
  STEAM_PLUGIN_DLL,
  findOuterpediaImagesDev,
} from "./paths.js";
import { resolveCaptureTarget, targetScriptArgs, loadManualDevice } from "./emulator-detect.js";
import { createApiHandler, serveStatic } from "./api-handler.js";
import { dlog, dwarn } from "./log.js";
import { ensureMitmdump, mitmdumpPath } from "./mitm-provision.js";
import { getStatus as getUpdateStatus, triggerCheck as triggerUpdateCheck, installUpdate } from "./updater.js";

/**
 * Content-Security-Policy for the renderer document. The prod build ships only
 * external module scripts (no inline/eval — that's a dev-only Vite thing), so
 * `script-src 'self'` is safe and silences Electron's insecure-CSP warning for
 * good. The few cross-origin holes are exactly the renderer's real needs:
 *   - style-src/font-src → Google Fonts (Geist + Geist Mono, loaded from
 *     index.html). 'unsafe-inline' on styles covers React's `style={{…}}` attrs.
 *   - img-src is same-origin only: every image goes through the `/img/*`
 *     route (bundled/cache/R2 proxying happens server-side, img-cache.ts).
 *     data:/blob: cover canvas/capture-derived images.
 * Everything else (game data, captured JSON, reco/update APIs, the solver
 * worker) is same-origin and falls under 'self'.
 */
const CSP = [
  "default-src 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: blob:",
  "connect-src 'self'",
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'self'",
  "frame-ancestors 'none'",
  "form-action 'none'",
].join("; ");

/** Resolve the args we hand capture.ps1 / disarm.ps1 so the bundled
 *  binaries are picked up in prod. In dev we pass nothing — the scripts
 *  fall back to their built-in defaults pointing at the LDPlayer-installed
 *  adb + the system mitmproxy + the dev's personal ~/.mitmproxy/ CA.
 *
 *  We resolve a target (manual override > running known brand > generic
 *  `adb devices` > installed-but-stopped) and override `-Adb` with its ADB
 *  (protocol versions differ across LDPlayer / MuMu / Nox vs our bundled one)
 *  and `-Device <serial>` so the script targets the right instance. */
async function captureScriptArgs(): Promise<string[]> {
  const target = await resolveCaptureTarget(loadManualDevice(MANUAL_DEVICE), BUNDLED_ADB);
  if (IS_DEV) return targetScriptArgs(target);
  return [
    "-Adb", target?.adbPath || BUNDLED_ADB,
    "-Mitmdump", mitmdumpPath(),
    "-Out", CAPTURE_OUT,
    // -MitmConfDir tells mitmdump where to load the matching CA from; -CertDir
    // tells capture.ps1 where to find the Android-hash cert file to push.
    // We point both at the same dir — the prod-cert tree generated by
    // fetch-binaries.mjs holds both files side by side.
    "-MitmConfDir", BUNDLED_PROD_CERT_DIR,
    "-CertDir", BUNDLED_PROD_CERT_DIR,
    ...(target?.device ? ["-Device", target.device] : []),
  ];
}

/** The shared API (api-handler.ts) wired to the packaged paths, the bundled
 *  binaries, mitmdump provisioning and electron-updater. */
const api = createApiHandler({
  captureDir: CAPTURE_DIR,
  captureOut: CAPTURE_OUT,
  derivedDir: DERIVED,
  repoShaState: REPO_SHA_STATE,
  statLocks: STAT_LOCKS,
  manualDevice: MANUAL_DEVICE,
  steamPluginDll: STEAM_PLUGIN_DLL,
  scratchDir: SCRATCH_DIR,
  bundledAdb: BUNDLED_ADB,
  img: {
    cacheDir: IMG_CACHE_DIR,
    bundledDir: BUNDLED_IMG,
    localCheckoutDir: IS_DEV ? findOuterpediaImagesDev() : null,
  },
  captureScriptArgs,
  prepareCapture: (log) => ensureMitmdump(log),
  update: { status: getUpdateStatus, check: triggerUpdateCheck, install: installUpdate },
});

export function handle(req: IncomingMessage, res: ServerResponse): void {
  if (api(req, res)) return;
  const url = (req.url ?? "/").split("?")[0]!;

  // --- renderer (built Vite dist) ---
  // SPA fallback: any unknown path serves index.html so client-side state
  // (currently tab name in usePersistedState) survives a hard reload.
  // Lock down the renderer document (the only thing CSP governs) on both the
  // direct and the fallback index.html serves.
  const headersFor = (file: string): Record<string, string> => (file.endsWith(".html") ? { "Content-Security-Policy": CSP } : {});
  const stripped = url === "/" ? "/index.html" : url;
  const file = normalize(join(RENDERER_DIST, stripped));
  if (file.startsWith(RENDERER_DIST) && existsSync(file) && statSync(file).isFile()) {
    serveStatic(req, res, file, "etag", headersFor(file));
    return;
  }
  const index = join(RENDERER_DIST, "index.html");
  serveStatic(req, res, index, "etag", headersFor(index));
}

/** Tear the capture pipeline down synchronously, if it's still armed. Used
 *  from main.ts on `before-quit` so the user doesn't have to remember to
 *  click Disarm before closing the window — otherwise `mitmdump.exe` and
 *  the device-side iptables redirect survive the Electron exit, and the
 *  next packaged build can't even delete its own bundled mitmdump (file in
 *  use), among other annoyances.
 *
 *  Returns true if a disarm was actually attempted (pipeline was armed).
 *  Uses `spawnSync` so the quit handler can await completion without
 *  needing to plumb a Promise through Electron's `before-quit` lifecycle. */
export async function disarmIfArmed(): Promise<boolean> {
  const pidFile = join(CAPTURE_OUT, ".mitm.pid");
  if (!existsSync(pidFile)) return false;
  dlog("capture", "armed at quit — running disarm.ps1");
  const args = await captureScriptArgs();
  // Async spawn (not spawnSync) so the caller's `await` yields to the event
  // loop instead of freezing it — `before-quit` runs this and a blocking
  // 15 s spawnSync would lock the UI thread for the whole teardown.
  await new Promise<void>((resolve) => {
    const child = spawn("powershell.exe", [
      "-ExecutionPolicy", "Bypass", "-NoLogo", "-NonInteractive",
      "-File", join(CAPTURE_DIR, "disarm.ps1"), ...args,
    ], { cwd: CAPTURE_DIR, windowsHide: true, stdio: "ignore" });
    const timer = setTimeout(() => {
      dwarn("capture", "disarm.ps1 exceeded 15s — killing it");
      try { child.kill(); } catch { /* already gone */ }
      resolve();
    }, 15_000);
    child.on("exit", () => { clearTimeout(timer); resolve(); });
    child.on("error", () => { clearTimeout(timer); resolve(); });
  });
  return true;
}

/** Preferred fixed port for the embedded HTTP server. We bind here so the
 *  renderer's URL (`http://127.0.0.1:<PREFERRED_PORT>/`) is stable across
 *  launches — otherwise localStorage (used for `gs.onboarding.done`,
 *  `gs.tab`, …) is scoped to a fresh origin every time and the user sees
 *  the wizard pop on every launch. Falls back to an ephemeral port if the
 *  preferred one is taken (e.g. another app squatted it). */
const PREFERRED_PORT = 17891;

/** Start the HTTP server on a stable 127.0.0.1 port (PREFERRED_PORT, or
 *  ephemeral fallback). Resolve with the chosen port so the caller can
 *  `loadURL("http://127.0.0.1:<port>/")`. */
export function startServer(): Promise<{ port: number; server: Server }> {
  return new Promise((resolve, reject) => {
    mkdirSync(CAPTURE_OUT, { recursive: true });
    const server = createServer(handle);
    const tryListen = (port: number, isFallback: boolean) => {
      server.removeAllListeners("error");
      const onError = (err: NodeJS.ErrnoException) => {
        if (!isFallback && err.code === "EADDRINUSE") {
          dlog("server", `port ${port} in use — falling back to an ephemeral port`);
          tryListen(0, true);
        } else {
          dwarn("server", "listen failed:", err.message);
          reject(err);
        }
      };
      server.on("error", onError);
      server.listen(port, "127.0.0.1", () => {
        const addr = server.address();
        if (addr && typeof addr === "object") {
          dlog("server", `listening on 127.0.0.1:${addr.port}${isFallback ? " (fallback)" : ""}`);
          resolve({ port: addr.port, server });
        } else reject(new Error("failed to bind"));
      });
    };
    tryListen(PREFERRED_PORT, false);
  });
}
